#!/usr/bin/env python3
"""Klicktest „Meine Ausgaben" (11.09.2026): Reiter im Projektkopf, Umwandlung ueber den
Export-Dialog, Link ins Regal, Unterseite /ausgaben (gefiltert + ungefiltert), Bericht/
Hoerprobe aufklappen, Dashboard-Abschnitt, Loeschen ohne Browser-Dialog, axe auf beiden Seiten.
Aufruf: /home/claude/.venv-pw/bin/python ui_ausgaben.py <projekt-id eines Word-Projekts>
Zugangsdaten aus INKLUDOCS_E2E_MAIL / INKLUDOCS_E2E_PW (~/.e2e.env)."""
import os, sys, json, re
from playwright.sync_api import sync_playwright
B = os.environ.get("INKLUDOCS_E2E_URL") or "https://staging.inkludocs.inklutec.de"
PID = sys.argv[1]
MAIL = os.environ.get("INKLUDOCS_E2E_MAIL", ""); PW = os.environ.get("INKLUDOCS_E2E_PW", "")
AXE = "https://cdn.jsdelivr.net/npm/axe-core@4.10.2/axe.min.js"
ok = fehler = 0
def check(n, c, i=""):
    global ok, fehler
    if c: ok += 1; print("  OK ", n)
    else: fehler += 1; print("  FEHLT", n, "--", str(i)[:300])
def axe(pg, name):
    pg.add_script_tag(url=AXE); pg.wait_for_timeout(500)
    r = pg.evaluate("async () => { const r = await axe.run(document, {runOnly:['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']}); return r.violations.map(v => ({id:v.id, impact:v.impact, n:v.nodes.length, html:v.nodes[0].html.slice(0,120)})); }")
    check(f"axe {name}: 0 Verstoesse", len(r) == 0, r)
os.makedirs("/home/claude/shots", exist_ok=True)
with sync_playwright() as p:
    br = p.chromium.launch(); ctx = br.new_context(viewport={"width": 1280, "height": 900}, locale="de-DE"); pg = ctx.new_page()
    pg.goto(B + "/login"); pg.fill("#email", MAIL); pg.fill("#password", PW); pg.keyboard.press("Enter"); pg.wait_for_timeout(2500)
    print("== A. Projektkopf: Reiter ==")
    pg.goto(B + f"/app?projekt={PID}"); pg.wait_for_timeout(3500)
    tabs = pg.locator("nav.proj-tabs a")
    check("nav.proj-tabs mit 2 Reitern (Dokumente, Ausgaben (n))", tabs.count() == 2 and tabs.nth(0).inner_text().strip() == "Dokumente" and re.match(r"Ausgaben \(\d+\)", tabs.nth(1).inner_text().strip()), [tabs.nth(i).inner_text() for i in range(tabs.count())])
    check("Reiter Dokumente traegt aria-current=page", tabs.nth(0).get_attribute("aria-current") == "page")
    check("nav hat aria-label Projektbereiche", pg.locator("nav.proj-tabs").get_attribute("aria-label") == "Projektbereiche")
    vorher = int(re.search(r"\((\d+)\)", tabs.nth(1).inner_text()).group(1))
    axe(pg, "Projektansicht mit Reitern")
    pg.screenshot(path="/home/claude/shots/a_reiter.png")
    print("== B. Umwandlung ueber den Export-Dialog ==")
    pg.locator("#exportOpenBtn").click(); pg.wait_for_timeout(800)
    pg.locator("#pdfuaBtn").click()
    for _ in range(120):
        pg.wait_for_timeout(1000)
        if pg.locator("#pdfuaDownload").count(): break
    check("Ergebnis mit Download-Knopf", pg.locator("#pdfuaDownload").count() == 1)
    link = pg.locator("#pdfuaAusgabenLink")
    check("Link „Zu meinen Ausgaben“ mit #ausgabe-<id>", link.count() == 1 and re.search(r"/ausgaben\?projekt=\d+#ausgabe-\d+", link.get_attribute("href") or ""), link.get_attribute("href") if link.count() else "")
    check("Satz zur Aufbewahrung im Ergebnis", "Meine Ausgaben" in pg.locator("#pdfuaResult").inner_text() and "Tage" in pg.locator("#pdfuaResult").inner_text())
    tab_txt = pg.locator("#ausgabenTab").inner_text().strip()
    check("Reiter-Zaehler um 1 erhoeht", tab_txt == f"Ausgaben ({vorher + 1})", (tab_txt, vorher))
    href = link.get_attribute("href"); aid = re.search(r"#ausgabe-(\d+)", href).group(1)
    pg.screenshot(path="/home/claude/shots/b_umwandlung.png")
    print("== C. Unterseite gefiltert (aus dem Export-Dialog) ==")
    link.click(); pg.wait_for_timeout(2500)
    check("URL /ausgaben?projekt=", f"/ausgaben?projekt={PID}" in pg.url, pg.url)
    h1 = pg.locator("h1").first.inner_text()
    check("H1 „Ausgaben: <Projektname>“", h1.startswith("Ausgaben: "), h1)
    check("Genau eine H1", pg.locator("h1").count() == 1)
    check("Zurueck-Link zum Projekt direkt unter der H1", pg.locator("#ausgabenZurueck a").inner_text().strip() == "Zurück zum Projekt" and f"/app?projekt={PID}" in (pg.locator("#ausgabenZurueck a").get_attribute("href") or ""))
    li = pg.locator(f"#ausgabe-{aid}")
    check("Eintrag #ausgabe-<id> vorhanden", li.count() == 1)
    check("Fokus auf der H2 des Eintrags (Sprungmarke)", pg.evaluate("() => document.activeElement && document.activeElement.tagName") == "H2")
    h2 = li.locator("h2").inner_text()
    check("H2 = Dokument — Datum, Uhrzeit", re.search(r" — .*\d{4}, \d{2}:\d{2}$", h2) is not None, h2)
    check("Vorschaubild mit Alt-Text", li.locator("img.ausgabe-vorschau").count() == 1 and (li.locator("img.ausgabe-vorschau").get_attribute("alt") or "").startswith("Vorschau der ersten Seite"), li.locator("img.ausgabe-vorschau").get_attribute("alt") if li.locator("img.ausgabe-vorschau").count() else "")
    check("Vorschaubild laedt (naturalWidth > 0)", li.locator("img.ausgabe-vorschau").evaluate("i => i.complete && i.naturalWidth > 0"))
    check("Pruefsatz (bestanden oder Hinweise)", li.locator("strong").first.inner_text().startswith("Prüfung: "), li.locator("strong").first.inner_text())
    dl = li.locator("a.btn-primary")
    check("Download-Link PDF herunterladen mit download-Attribut", dl.count() == 1 and dl.inner_text().strip() in ("PDF herunterladen", "ZIP herunterladen") and dl.get_attribute("download") is not None and f"/api/ausgaben/{aid}/datei" in (dl.get_attribute("href") or ""), (dl.inner_text() if dl.count() else "", dl.get_attribute("href") if dl.count() else ""))
    check("„Datei verfuegbar bis“ + „Zum Projekt“ + „Loeschen“", "Datei verfügbar bis" in li.inner_text() and li.locator("a:has-text('Zum Projekt')").count() == 1 and li.locator("button:has-text('Löschen')").count() == 1)
    # Bericht aufklappen (wird erst jetzt geladen)
    det = li.locator("details.ausgabe-bericht"); det.locator("summary").first.click(); pg.wait_for_timeout(1500)
    check("Bericht lesen: Liste mit Bereichen (Struktur, Text, Bilder ...)", det.locator("li").count() >= 5 and "Bilder und Grafiken" in det.inner_text(), det.inner_text()[:200])
    det2 = li.locator("details.ausgabe-hoerprobe-details"); det2.locator("summary").first.click(); pg.wait_for_timeout(1000)
    check("Hoerprobe lesen: Zeilen vorhanden, Bereich fokussierbar", det2.locator(".ausgabe-hoerprobe p").count() >= 3 and det2.locator(".ausgabe-hoerprobe").first.get_attribute("tabindex") == "0", det2.locator(".ausgabe-hoerprobe p").count())
    check("Filter zeigt das Projekt vorausgewaehlt", pg.locator("#projektFilter").evaluate("s => s.value") == str(PID))
    axe(pg, "Ausgaben-Seite gefiltert (Bericht + Hoerprobe offen)")
    pg.screenshot(path="/home/claude/shots/c_ausgaben_projekt.png", full_page=True)
    print("== D. Unterseite ungefiltert + Seitenleiste ==")
    pg.goto(B + "/ausgaben"); pg.wait_for_timeout(2500)
    check("H1 „Meine Ausgaben“", pg.locator("h1").first.inner_text().strip() == "Meine Ausgaben")
    nav = pg.locator("#appSidebar nav a:has-text('Meine Ausgaben')")
    check("Seitenleiste: Eintrag „Meine Ausgaben“ mit aria-current", nav.count() == 1 and nav.get_attribute("aria-current") == "page")
    check("Zurueck zur Startseite", pg.locator("#ausgabenZurueck a").inner_text().strip() == "Zurück zur Startseite")
    check("Eintrag auch in der Gesamtliste, Projektname in der Meta-Zeile", pg.locator(f"#ausgabe-{aid}").count() == 1 and pg.locator(f"#ausgabe-{aid} .dash-meta").first.inner_text().strip() != "")
    check("Intro nennt die Aufbewahrung in Tagen", re.search(r"\d+ Tage", pg.locator("#ausgabenIntro").inner_text()) is not None, pg.locator("#ausgabenIntro").inner_text())
    axe(pg, "Ausgaben-Seite ungefiltert")
    pg.screenshot(path="/home/claude/shots/d_ausgaben_alle.png", full_page=True)
    print("== E. Dashboard ==")
    pg.goto(B + "/dashboard"); pg.wait_for_timeout(2500)
    sec = pg.locator("#ausgabenSection")
    check("Abschnitt „Neueste Ausgaben“ sichtbar mit Eintrag", sec.count() == 1 and not sec.evaluate("s => s.hidden") and sec.locator("li").count() >= 1, sec.evaluate("s => s.hidden") if sec.count() else "kein Abschnitt")
    check("Link im Dashboard fuehrt zu /ausgaben?projekt=…#ausgabe-…", re.search(r"/ausgaben\?projekt=\d+#ausgabe-\d+", sec.locator("li a").first.get_attribute("href") or "") is not None)
    check("„Alle Ausgaben anzeigen“", sec.locator("a:has-text('Alle Ausgaben anzeigen')").count() == 1)
    axe(pg, "Dashboard mit Neueste Ausgaben")
    pg.screenshot(path="/home/claude/shots/e_dashboard.png")
    print("== F. Loeschen ohne Browser-Dialog ==")
    pg.goto(B + f"/ausgaben?projekt={PID}"); pg.wait_for_timeout(2500)
    li = pg.locator(f"#ausgabe-{aid}")
    li.locator("button:has-text('Löschen')").click(); pg.wait_for_timeout(300)
    check("Rueckfrage mit Ja/Abbrechen im Eintrag", li.locator("button:has-text('Ja, löschen')").count() == 1 and li.locator("button:has-text('Abbrechen')").count() == 1 and "Wirklich löschen?" in li.inner_text())
    li.locator("button:has-text('Abbrechen')").click(); pg.wait_for_timeout(300)
    check("Abbrechen stellt den Loeschen-Knopf wieder her", li.locator("button:has-text('Löschen')").count() == 1 and li.locator("button:has-text('Ja, löschen')").count() == 0)
    li.locator("button:has-text('Löschen')").click(); pg.wait_for_timeout(300)
    li.locator("button:has-text('Ja, löschen')").click(); pg.wait_for_timeout(1500)
    check("Eintrag nach dem Loeschen weg", pg.locator(f"#ausgabe-{aid}").count() == 0)
    pg.goto(B + f"/app?projekt={PID}"); pg.wait_for_timeout(3000)
    check("Reiter-Zaehler wieder auf Ausgangswert", pg.locator("#ausgabenTab").inner_text().strip() == f"Ausgaben ({vorher})", pg.locator("#ausgabenTab").inner_text())
    br.close()
print(f"Ergebnis: {ok} OK, {fehler} FEHLER")
sys.exit(1 if fehler else 0)
