#!/usr/bin/env python3
"""Klicktest „Meine Ausgaben" (11.09.2026): Reiter im Projektkopf, Umwandlung ueber den
Export-Dialog, Link ins Regal, Unterseite /ausgaben (gefiltert + ungefiltert), Bericht/
Hoerprobe aufklappen, Dashboard-Abschnitt, Loeschen ohne Browser-Dialog, axe auf beiden Seiten.
Aufruf: /home/claude/.venv-pw/bin/python ui_ausgaben.py <projekt-id eines Word-Projekts>
Zugangsdaten aus INKLUDOCS_E2E_MAIL / INKLUDOCS_E2E_PW (~/.e2e.env)."""
import os, sys, json, re
from playwright.sync_api import sync_playwright
B = os.environ.get("INKLUDOCS_E2E_URL") or "https://staging.inkludocs.inklutec.de"
PID = sys.argv[1]
MAIL = os.environ.get("INKLUDOCS_E2E_MAIL", ""); PW = os.environ.get("INKLUDOCS_E2E_PW", "")
AXE = "https://cdn.jsdelivr.net/npm/axe-core@4.10.2/axe.min.js"
ok = fehler = 0
def check(n, c, i=""):
    global ok, fehler
    if c: ok += 1; print("  OK ", n)
    else: fehler += 1; print("  FEHLT", n, "--", str(i)[:300])
def axe(pg, name):
    pg.add_script_tag(url=AXE); pg.wait_for_timeout(500)
    r = pg.evaluate("async () => { const r = await axe.run(document, {runOnly:['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22aa']}); return r.violations.map(v => ({id:v.id, impact:v.impact, n:v.nodes.length, html:v.nodes[0].html.slice(0,120)})); }")
    check(f"axe {name}: 0 Verstoesse", len(r) == 0, r)
os.makedirs("/home/claude/shots", exist_ok=True)
with sync_playwright() as p:
    br = p.chromium.launch(); ctx = br.new_context(viewport={"width": 1280, "height": 900}, locale="de-DE"); pg = ctx.new_page()
    pg.goto(B + "/login"); pg.fill("#email", MAIL); pg.fill("#password", PW); pg.keyboard.press("Enter"); pg.wait_for_timeout(2500)
    print("== A. Projektkopf: Ausgaben-Knopf ==")
    pg.goto(B + f"/app?projekt={PID}"); pg.wait_for_timeout(3500)
    tab = pg.locator("#ausgabenTab")
    check("Knopf-Link „Ablage (n)“ rechts neben Herunterladen (Steve/Michael 11.09.)", tab.count() == 1 and re.match(r"Ablage \(\d+\)", tab.inner_text().strip()) and (tab.get_attribute("href") or "").startswith("/ablage?projekt="), tab.inner_text() if tab.count() else "")
    check("Kein Reiter „Dokumente“ mehr", pg.locator("nav.proj-tabs").count() == 0)
    check("Ausgaben-Link steht in derselben Aktionszeile wie Herunterladen", pg.evaluate("() => document.getElementById('ausgabenTab').parentElement === document.getElementById('exportOpenBtn').parentElement"))
    vorher = int(re.search(r"\((\d+)\)", tab.inner_text()).group(1))
    axe(pg, "Projektansicht mit Reitern")
    pg.screenshot(path="/home/claude/shots/a_reiter.png")
    print("== B. Umwandlung ueber den Export-Dialog ==")
    pg.locator("#exportOpenBtn").click(); pg.wait_for_timeout(800)
    pg.locator("#pdfuaBtn").click()
    for _ in range(120):
        pg.wait_for_timeout(1000)
        if pg.locator("#pdfuaDownload").count(): break
    check("Ergebnis mit Download-Knopf", pg.locator("#pdfuaDownload").count() == 1)
    link = pg.locator("#pdfuaAusgabenLink")
    check("Link „Zur Ablage“ mit #ausgabe-<id>", link.count() == 1 and re.search(r"/ablage\?projekt=\d+#ausgabe-\d+", link.get_attribute("href") or ""), link.get_attribute("href") if link.count() else "")
    # Michael Karbe (Mail 12.09.2026): Abbrechen unten rechts, „Zur Ablage“ direkt links daneben — beide in der Dialog-Fusszeile.
    check("„Zur Ablage“ und „Abbrechen“ stehen zusammen unten rechts (exportFooter, Link direkt vor dem Knopf)", pg.evaluate("() => { const a = document.getElementById('pdfuaAusgabenLink'), b = document.getElementById('exportCancelBtn'), f = document.getElementById('exportFooter'); return !!(a && b && f && a.parentElement === f && b.parentElement === f && a.nextElementSibling === b && getComputedStyle(f).justifyContent === 'flex-end'); }"))
    check("Abbrechen ist der letzte Knopf im Dialog", pg.evaluate("() => { const bs = document.querySelectorAll('#exportPanel button'); return bs[bs.length - 1].id === 'exportCancelBtn'; }"))
    check("Kein „Zur Ablage“ mehr in der Ergebnisbox", pg.locator("#pdfuaResult a").count() == 0)
    check("Satz „liegen jetzt in deiner Ablage“, kein Aufbewahrungs-Satz, keine „in Ordnung“-Zeilen", "in deiner Ablage" in pg.locator("#pdfuaResult").inner_text() and "Tage" not in pg.locator("#pdfuaResult").inner_text() and "in Ordnung" not in pg.locator("#pdfuaResult").inner_text())
    tab_txt = pg.locator("#ausgabenTab").inner_text().strip()
    check("Ablage-Zaehler um 1 erhoeht", tab_txt == f"Ablage ({vorher + 1})", (tab_txt, vorher))
    href = link.get_attribute("href"); aid = re.search(r"#ausgabe-(\d+)", href).group(1)
    pg.screenshot(path="/home/claude/shots/b_umwandlung.png")
    print("== C. Unterseite gefiltert (aus dem Export-Dialog) ==")
    link.click(); pg.wait_for_timeout(2500)
    check("URL /ablage?projekt=", f"/ablage?projekt={PID}" in pg.url, pg.url)
    h1 = pg.locator("h1").first.inner_text()
    check("H1 „Ablage: <Projektname>“", h1.startswith("Ablage: "), h1)
    check("Genau eine H1", pg.locator("h1").count() == 1)
    check("Kein Zurueck-Knopf (Besprechung 11.09.)", pg.locator("#ausgabenZurueck").count() == 0 and pg.locator("main a:has-text('Zurück')").count() == 0)
    check("Einleitung: Sicherung … inklusive Prüfbericht", "inklusive Prüfbericht" in pg.locator("#ausgabenIntro").inner_text())
    li = pg.locator(f"#ausgabe-{aid}")
    check("Eintrag #ausgabe-<id> vorhanden", li.count() == 1)
    check("Fokus auf der H2 des Eintrags (Sprungmarke)", pg.evaluate("() => document.activeElement && document.activeElement.tagName") == "H2")
    h2 = li.locator("h2").inner_text()
    check("H2 = Art: Dokument — Datum, Uhrzeit (Art sichtbar, Michael 11.09.)", h2.startswith("Barrierefreie PDF: ") and re.search(r" — .*\d{4}, \d{2}:\d{2}$", h2) is not None, h2)
    check("Vorschaubild mit Alt-Text", li.locator("img.ausgabe-vorschau").count() == 1 and (li.locator("img.ausgabe-vorschau").get_attribute("alt") or "").startswith("Vorschau der ersten Seite"), li.locator("img.ausgabe-vorschau").get_attribute("alt") if li.locator("img.ausgabe-vorschau").count() else "")
    check("Vorschaubild laedt (naturalWidth > 0)", li.locator("img.ausgabe-vorschau").evaluate("i => i.complete && i.naturalWidth > 0"))
    check("Pruefsatz nur Befunde (PDF/UA bestanden, keine Befunde / n Bereiche mit Befunden)", "Befunde" in li.locator("strong").first.inner_text(), li.locator("strong").first.inner_text())
    dl = li.locator("a.btn-primary")
    check("Download-Link PDF herunterladen mit download-Attribut", dl.count() == 1 and dl.inner_text().strip() in ("PDF herunterladen", "ZIP herunterladen") and dl.get_attribute("download") is not None and f"/api/ausgaben/{aid}/datei" in (dl.get_attribute("href") or ""), (dl.inner_text() if dl.count() else "", dl.get_attribute("href") if dl.count() else ""))
    check("Kein „verfuegbar bis“ (unbegrenzt) + „Zum Projekt“ + „Loeschen“", "verfügbar bis" not in li.inner_text() and li.locator("a:has-text('Zum Projekt')").count() == 1 and li.locator("button:has-text('Löschen')").count() == 1)
    # Bericht aufklappen (wird erst jetzt geladen)
    det = li.locator("details.ausgabe-bericht"); det.locator("summary").first.click(); pg.wait_for_timeout(1500)
    check("Bericht lesen: nur Befunde oder „Keine Befunde“ (keine „in Ordnung“-Zeilen)", "in Ordnung" not in det.inner_text() and ("Befunde" in det.inner_text()), det.inner_text()[:200])
    det2 = li.locator("details.ausgabe-hoerprobe-details"); det2.locator("summary").first.click(); pg.wait_for_timeout(1000)
    check("Hoerprobe lesen: Zeilen vorhanden, Bereich fokussierbar", det2.locator(".ausgabe-hoerprobe p").count() >= 3 and det2.locator(".ausgabe-hoerprobe").first.get_attribute("tabindex") == "0", det2.locator(".ausgabe-hoerprobe p").count())
    check("Filter zeigt das Projekt vorausgewaehlt", pg.locator("#projektFilter").evaluate("s => s.value") == str(PID))
    axe(pg, "Ausgaben-Seite gefiltert (Bericht + Hoerprobe offen)")
    pg.screenshot(path="/home/claude/shots/c_ausgaben_projekt.png", full_page=True)
    print("== D. Unterseite ungefiltert + Seitenleiste ==")
    pg.goto(B + "/ablage"); pg.wait_for_timeout(2500)
    check("H1 „Meine Ablage“", pg.locator("h1").first.inner_text().strip() == "Meine Ablage")
    nav = pg.locator("#appSidebar nav a:has-text('Meine Ablage')")
    check("Seitenleiste: Eintrag „Meine Ablage“ mit aria-current", nav.count() == 1 and nav.get_attribute("aria-current") == "page")
    pg.goto(B + "/ausgaben?projekt=" + str(PID)); pg.wait_for_timeout(1500)
    check("Alter Pfad /ausgaben leitet auf /ablage (Chat-Verlauf von vormittags)", "/ablage?projekt=" in pg.url, pg.url)
    pg.goto(B + "/ablage"); pg.wait_for_timeout(2500)
    check("Eintrag auch in der Gesamtliste, Projektname in der Meta-Zeile", pg.locator(f"#ausgabe-{aid}").count() == 1 and pg.locator(f"#ausgabe-{aid} .dash-meta").first.inner_text().strip() != "")
    check("Intro ohne Aufbewahrungsfrist", "Tage" not in pg.locator("#ausgabenIntro").inner_text(), pg.locator("#ausgabenIntro").inner_text())
    axe(pg, "Ausgaben-Seite ungefiltert")
    pg.screenshot(path="/home/claude/shots/d_ausgaben_alle.png", full_page=True)
    print("== E. Dashboard ==")
    pg.goto(B + "/dashboard"); pg.wait_for_timeout(2500)
    sec = pg.locator("#ausgabenSection")
    check("Abschnitt „Neu in der Ablage“ sichtbar mit Eintrag", sec.count() == 1 and not sec.evaluate("s => s.hidden") and sec.locator("li").count() >= 1 and "Neu in der Ablage" in sec.inner_text(), sec.evaluate("s => s.hidden") if sec.count() else "kein Abschnitt")
    check("Link im Dashboard fuehrt zu /ablage?projekt=…#ausgabe-…", re.search(r"/ablage\?projekt=\d+#ausgabe-\d+", sec.locator("li a").first.get_attribute("href") or "") is not None)
    check("„Ablage öffnen“", sec.locator("a:has-text('Ablage öffnen')").count() == 1)
    axe(pg, "Dashboard mit Neueste Ausgaben")
    pg.screenshot(path="/home/claude/shots/e_dashboard.png")
    print("== F. Loeschen ohne Browser-Dialog ==")
    pg.goto(B + f"/ablage?projekt={PID}"); pg.wait_for_timeout(2500)
    li = pg.locator(f"#ausgabe-{aid}")
    li.locator("button:has-text('Löschen')").click(); pg.wait_for_timeout(300)
    check("Rueckfrage mit Ja/Abbrechen im Eintrag", li.locator("button:has-text('Ja, löschen')").count() == 1 and li.locator("button:has-text('Abbrechen')").count() == 1 and "Wirklich löschen?" in li.inner_text())
    li.locator("button:has-text('Abbrechen')").click(); pg.wait_for_timeout(300)
    check("Abbrechen stellt den Loeschen-Knopf wieder her", li.locator("button:has-text('Löschen')").count() == 1 and li.locator("button:has-text('Ja, löschen')").count() == 0)
    li.locator("button:has-text('Löschen')").click(); pg.wait_for_timeout(300)
    li.locator("button:has-text('Ja, löschen')").click(); pg.wait_for_timeout(1500)
    check("Eintrag nach dem Loeschen weg", pg.locator(f"#ausgabe-{aid}").count() == 0)
    pg.goto(B + f"/app?projekt={PID}"); pg.wait_for_timeout(3000)
    check("Ablage-Zaehler wieder auf Ausgangswert", pg.locator("#ausgabenTab").inner_text().strip() == f"Ablage ({vorher})", pg.locator("#ausgabenTab").inner_text())
    br.close()
print(f"Ergebnis: {ok} OK, {fehler} FEHLER")
sys.exit(1 if fehler else 0)
