#!/usr/bin/env python3
"""Klicktest Quickinfo-Werkzeug (27.08.2026): Werkzeugauswahl, Formular-Ansicht
(Dokument/Seite/Feld-Struktur, Kontext, Auto-Save, Stammdaten-Knoepfe,
Hoerprobe, Filter, Export-Dialog), axe. Muster: ui_word.py.
Aufruf: /home/claude/.venv-pw/bin/python ui_formular.py <projekt-id> [gast-token]
Gast-Ansicht (28.08.2026): mit Token wird zusaetzlich /freigabe/<token> geprueft."""
import sys
from playwright.sync_api import sync_playwright
import os
B = os.environ.get("INKLUDOCS_E2E_URL", "https://staging.inkludocs.inklutec.de"); PID = sys.argv[1]; TOKEN = sys.argv[2] if len(sys.argv) > 2 else ""
MAIL, PW = os.environ.get("INKLUDOCS_E2E_MAIL", ""), os.environ.get("INKLUDOCS_E2E_PW", "")
if not MAIL or not PW: sys.exit("Zugangsdaten fehlen: INKLUDOCS_E2E_MAIL / INKLUDOCS_E2E_PW setzen")
SHOTS = os.environ.get("INKLUDOCS_E2E_SHOTS", "/tmp")
AXE = "https://cdn.jsdelivr.net/npm/axe-core@4.10.2/axe.min.js"
ok = fehler = 0
def check(n, c, i=""):
    global ok, fehler
    if c: ok += 1; print("  OK ", n)
    else: fehler += 1; print("  FEHLT", n, "--", i)
with sync_playwright() as p:
    br = p.chromium.launch(); ctx = br.new_context(viewport={"width": 1280, "height": 900}, locale="de-DE"); pg = ctx.new_page()
    fehler_js = []
    pg.on("pageerror", lambda e: fehler_js.append(str(e)))
    pg.goto(B + "/"); pg.fill("#email", MAIL); pg.fill("#password", PW); pg.keyboard.press("Enter"); pg.wait_for_timeout(2500)
    print("== A. Werkzeugauswahl ==")
    pg.goto(B + "/projekt-neu"); pg.wait_for_timeout(1500)
    opts = pg.locator("#toolSelect option").all_text_contents()
    check("Quickinfo-Werkzeug im Auswahlmenue", any("Quickinfos" in o for o in opts), opts)
    print("== B. Formular-Ansicht ==")
    pg.goto(B + f"/app?projekt={PID}"); pg.wait_for_timeout(3500)
    main = pg.locator("main")
    check("H1 Projektname", pg.locator("h1#projectName").count() == 1)
    check("Kopfzeile nennt Felder und Stammdaten", "Felder" in pg.locator("#projectHeadInfo").inner_text() and "Stammdaten" in pg.locator("#projectHeadInfo").inner_text(), pg.locator("#projectHeadInfo").inner_text())
    check("Upload-Block: Weiteres PDF-Formular hinzufuegen", pg.locator("#addHeading").inner_text().strip() == "Weiteres PDF-Formular hinzufügen", pg.locator("#addHeading").inner_text())
    check("Dateiauswahl akzeptiert .pdf", pg.locator("#projUpload").get_attribute("accept") == ".pdf")
    check("Kein 'Bilder' in der Formular-Ansicht", "Bilder" not in main.inner_text(), "")
    docs = pg.locator("h2.doc-heading"); check("Dokument-Ueberschrift (h2) mit Felder-Zaehler", docs.count() == 1 and "Felder" in docs.first.inner_text(), docs.first.inner_text() if docs.count() else "")
    pg.locator("details.doc-section").first.evaluate("d=>d.open=true"); pg.wait_for_timeout(300)
    check("Hoerprobe-Klappe vorhanden", pg.locator("details.doc-hoerprobe").count() == 1)
    pg.locator("details.doc-hoerprobe").first.evaluate("d=>d.open=true"); pg.wait_for_timeout(200)
    hp = pg.locator("details.doc-hoerprobe ol li")
    check("Hoerprobe listet 12 Felder", hp.count() == 12, hp.count())
    check("Hoerprobe: offene Felder als 'ohne Bezeichnung'", "ohne Bezeichnung" in pg.locator("details.doc-hoerprobe").inner_text())
    h3 = pg.locator("h3.page-heading"); check("Seiten-Ueberschriften (h3) 'Seite N'", h3.count() == 2 and h3.first.inner_text().startswith("Seite 1"), [h3.nth(i).inner_text() for i in range(h3.count())])
    pg.locator("details.page-section").first.evaluate("d=>d.open=true"); pg.wait_for_timeout(300)
    check("Seitenansicht-Klappe", pg.locator("details.page-section").first.locator("details.page-view-details").count() == 1)
    check("Seitentext-Klappe", pg.locator("details.page-section").first.locator("details.page-text-details").count() >= 1)
    h4 = pg.locator("details.page-section").first.locator("h4.image-heading")
    check("Feld-Ueberschriften h4 'Feld N, Feldart, Seite P'", h4.count() >= 8 and h4.first.inner_text().startswith("Feld 1, Textfeld, Seite 1"), h4.first.inner_text() if h4.count() else "")
    card = pg.locator("section.feld-review").first
    check("Kontextabsatz mit Beschriftung und Abschnitt", "Beschriftung im Formular: Vorname" in card.locator("p.feld-kontext").inner_text() and "Abschnitt: Angaben zum Kontoinhaber" in card.locator("p.feld-kontext").inner_text(), card.locator("p.feld-kontext").inner_text())
    ta = card.locator("textarea.quickinfo-field")
    check("Textarea Quickinfo mit aria-describedby auf Kontext", ta.get_attribute("aria-describedby") == "feld_kontext_" + card.get_attribute("id").split("_")[1])
    check("Ausschnitt-Bild dekorativ (alt leer)", card.locator("img.feld-ausschnitt").get_attribute("alt") == "")
    check("Badge 'von Hand'/'vom Gast bearbeitet' am bearbeiteten Feld", ("von Hand" in card.locator(".image-review-header").inner_text()) or ("vom Gast bearbeitet" in card.locator(".image-review-header").inner_text()), card.locator(".image-review-header").inner_text())
    # Pflichtfeld-Badge am Geburtsdatum (Feld 4)
    geb = pg.locator("section.feld-review").nth(3)
    check("Pflichtfeld-Badge", "Pflichtfeld" in geb.locator(".image-review-header").inner_text(), geb.locator(".image-review-header").inner_text())
    kn = pg.locator("section.feld-review").nth(5)
    check("Badge 'bereits ausgefuellt' (Kundennummer)", "bereits ausgefüllt" in kn.locator(".image-review-header").inner_text())
    check("Feldwert nirgends auf der Seite", "K-0000" not in main.inner_text())
    print("== C. Auto-Save + Knoepfe ==")
    ta.fill("Vorname des Kontoinhabers, wie im Ausweis"); pg.wait_for_timeout(1500)
    check("Gespeichert-Anzeige sichtbar", "visible" in (card.locator(".save-indicator").get_attribute("class") or ""))
    pg.reload(); pg.wait_for_timeout(3000)
    pg.locator("details.doc-section").first.evaluate("d=>d.open=true"); pg.locator("details.page-section").first.evaluate("d=>d.open=true"); pg.wait_for_timeout(300)
    card = pg.locator("section.feld-review").first
    check("Wert nach Neuladen erhalten", card.locator("textarea.quickinfo-field").input_value() == "Vorname des Kontoinhabers, wie im Ausweis", card.locator("textarea.quickinfo-field").input_value())
    # In Stammdaten uebernehmen
    card.locator("button:has-text('In Stammdaten übernehmen')").click(); pg.wait_for_timeout(1200)
    check("Meldung 'In deine Stammdaten uebernommen'", "übernommen" in card.locator("[id^=feld_msg_]").inner_text(), card.locator("[id^=feld_msg_]").inner_text())
    # Zurueck auf Original beim E-Mail-Feld (Feld 5)
    em = pg.locator("section.feld-review").nth(4)
    em.locator("textarea.quickinfo-field").fill("geaendert"); pg.wait_for_timeout(1200)
    em.locator("button:has-text('Zurück auf Original')").click(); pg.wait_for_timeout(800)
    check("Zurueck auf Original stellt PDF-Quickinfo her", em.locator("textarea.quickinfo-field").input_value() == "E-Mail-Adresse für Kontoauszüge", em.locator("textarea.quickinfo-field").input_value())
    print("== C2. Stufe 2: Generieren am Feld ==")
    # Ein OFFENES Feld (nachname traegt inzwischen einen im Chat bestaetigten Text, der bleibt — KI-Fach)
    pg.locator("details.doc-section").evaluate_all("ds=>ds.forEach(d=>d.open=true)"); pg.locator("details.page-section").evaluate_all("ds=>ds.forEach(d=>d.open=true)"); pg.wait_for_timeout(300)
    # Deterministisch per JS: erste Karte mit leerem, beschreibbarem Textfeld; notfalls (Wiederholungslauf) eine leeren
    JS_LEER = "[...document.querySelectorAll('section.feld-review')].filter(c=>{const t=c.querySelector('textarea.quickinfo-field');return t&&!t.disabled&&!t.value.trim();}).map(c=>c.id)"
    leer = pg.evaluate(JS_LEER)
    if not leer:
        pg.evaluate("(()=>{const cs=[...document.querySelectorAll('section.feld-review')].filter(c=>{const t=c.querySelector('textarea.quickinfo-field');return t&&!t.disabled;});const t=cs[2].querySelector('textarea.quickinfo-field');t.value='';t.dispatchEvent(new Event('input',{bubbles:true}));})()")
        pg.wait_for_timeout(1500); leer = pg.evaluate(JS_LEER)
    nn = pg.locator("#" + leer[0])
    check("Knopf Generieren/Neu generieren vorhanden", nn.locator("button[id^=feld_gen_]").count() == 1)
    check("Knopf Alle generieren im Kopf (offene Felder vorhanden)", pg.locator("#fGenAllBtn").count() == 1)
    check("Kein zweiter Knopf: ein Knopf wechselt zwischen Alle generieren / Alle neu generieren", pg.locator("#fGenKiBtn").count() == 0 and pg.locator("#fGenAllBtn").inner_text().strip().startswith("Alle generieren"))
    check("Sprache der Quickinfos + Gespeicherte Prompts vorhanden", pg.locator("#altLangSelect").count() == 1 and pg.locator("#ownPromptSelect").count() == 1)
    vorher = nn.locator("textarea.quickinfo-field").input_value()
    nn.locator("button[id^=feld_gen_]").click()
    text = ""
    for _ in range(45):
        pg.wait_for_timeout(1000)
        text = nn.locator("textarea.quickinfo-field").input_value()
        if text and text != vorher: break
    check("KI-Text im Feld (>3 Zeichen, anders als vorher)", len(text) > 3 and text != vorher, (text, nn.locator("h4").inner_text(), nn.locator("[id^=feld_msg_]").inner_text()))
    print("      KI:", text)
    check("Badge KI-Vorschlag mit Sicherheit", "KI-Vorschlag" in nn.locator("[id^=feld_status_]").inner_text(), nn.locator("[id^=feld_status_]").inner_text())
    check("Beleg-Satz sichtbar", nn.locator("[id^=feld_beleg_]").count() == 1 and not nn.locator("[id^=feld_beleg_]").evaluate("e=>e.hidden") and len(nn.locator("[id^=feld_beleg_]").inner_text()) > 5, nn.locator("[id^=feld_beleg_]").inner_text())
    check("Knopf heisst jetzt Neu generieren", nn.locator("button[id^=feld_gen_]").inner_text().strip() == "Neu generieren")
    check("Filter Nur unsichere vorhanden", pg.locator("#fNurUnsichere").count() == 1)
    # KI-Fach: Feld 1 (Hand-Text) -> Generieren laesst den Text stehen, Knopf 'KI-Vorschlag uebernehmen' erscheint
    c1 = pg.locator("section.feld-review").first
    vorher1 = c1.locator("textarea.quickinfo-field").input_value()
    check("KI-Knopf vorher versteckt", c1.locator("button[id^=feld_ki_]").evaluate("b=>b.hidden") is True)
    c1.locator("button[id^=feld_gen_]").click()
    for _ in range(45):
        pg.wait_for_timeout(1000)
        if c1.locator("button[id^=feld_ki_]").evaluate("b=>!b.hidden"): break
    check("Hand-Text bleibt nach Generieren", c1.locator("textarea.quickinfo-field").input_value() == vorher1, c1.locator("textarea.quickinfo-field").input_value())
    check("Knopf 'KI-Vorschlag uebernehmen' sichtbar + Meldung", c1.locator("button[id^=feld_ki_]").evaluate("b=>!b.hidden") and "dein Text bleibt" in c1.locator("[id^=feld_msg_]").inner_text(), c1.locator("[id^=feld_msg_]").inner_text())
    c1.locator("button[id^=feld_ki_]").click(); pg.wait_for_timeout(1000)
    # (Der KI-Text kann dem Hand-Text gleichen — die bestaetigte Fassung gilt als Vorgabe; entscheidend: Badge KI, Knopf weg)
    check("KI-Vorschlag uebernommen (Badge KI, Knopf versteckt)", "KI-Vorschlag" in c1.locator("[id^=feld_status_]").inner_text() and c1.locator("button[id^=feld_ki_]").evaluate("b=>b.hidden") is True, c1.locator("[id^=feld_status_]").inner_text())
    print("== D. Filter ==")
    pg.locator("#fNurOffene").check(); pg.wait_for_timeout(400)
    sichtbar = pg.locator("section.feld-review:not([hidden])").count(); alle = pg.locator("section.feld-review").count()
    check("Filter 'Nur offene' blendet beschriebene aus", 0 < sichtbar < alle, (sichtbar, alle))
    pg.locator("#fNurOffene").uncheck(); pg.wait_for_timeout(300)
    print("== E. Export-Dialog ==")
    pg.locator("#fExportOpenBtn").click(); pg.wait_for_timeout(800)
    dlg = pg.locator("#fExportPanel")
    check("Export-Dialog offen (modal)", dlg.evaluate("d=>d.open") is True)
    check("Zusammenfassung nennt Felder", "Feldern" in pg.locator("#fExportSummary").inner_text(), pg.locator("#fExportSummary").inner_text())
    pg.wait_for_timeout(800)
    check("Zusammenfassung nennt den Export-Preis (Credits)", "Credits" in pg.locator("#fExportSummary").inner_text(), pg.locator("#fExportSummary").inner_text())
    check("Knopf 'Als PDF mit Quickinfos'", dlg.locator("button:has-text('Als PDF mit Quickinfos')").count() == 1)
    check("Knopf 'Als CSV (Feldliste)'", dlg.locator("button:has-text('Als CSV (Feldliste)')").count() == 1)
    with pg.expect_download(timeout=30000) as dl:
        dlg.locator("button:has-text('Als PDF mit Quickinfos')").click()
    d = dl.value
    check("PDF-Download", d.suggested_filename.endswith("_quickinfos.pdf"), d.suggested_filename)
    pg.wait_for_timeout(800)
    check("Dialog nach Export geschlossen", dlg.evaluate("d=>d.open") is False)
    # Credits-Meldung (Export-Staffel 28.08.2026): barrierefreies Modal mit beiden Zahlen und zwei Knoepfen
    pg.evaluate("zeigeCreditsMeldung({preis: 8, verfuegbar: 7})"); pg.wait_for_timeout(500)
    cd_ = pg.locator("#creditsDialog")
    check("Credits-Meldung offen (modal), Fokus auf Ueberschrift", cd_.evaluate("d=>d.open") is True and pg.evaluate("document.activeElement && document.activeElement.id === 'creditsHeading'"))
    check("Credits-Meldung nennt 8 und 7 Credits", "8 Credits" in cd_.inner_text() and "7 Credits" in cd_.inner_text(), cd_.inner_text())
    check("Knoepfe Zu Abo & Verbrauch (Link /abo) + Schliessen", cd_.locator("a[href='/abo']").count() == 1 and cd_.locator("#creditsClose").count() == 1)
    pg.locator("#creditsClose").click(); pg.wait_for_timeout(300)
    check("Credits-Meldung geschlossen", cd_.evaluate("d=>d.open") is False)
    pg.screenshot(path=os.path.join(SHOTS, "f_projekt.png"), full_page=False)
    print("== F. axe ==")
    pg.add_script_tag(url=AXE); pg.wait_for_timeout(500)
    pg.locator("details.doc-section").first.evaluate("d=>d.open=true"); pg.locator("details.page-section").first.evaluate("d=>d.open=true")
    res = pg.evaluate("axe.run(document, {runOnly:{type:'tag', values:['wcag2a','wcag2aa','wcag21a','wcag21aa']}}).then(r=>r.violations.map(v=>v.id+': '+v.nodes.length+' '+v.nodes.slice(0,2).map(n=>n.target.join(' ')).join(' | ')))")
    check("axe 0 Verstoesse Formular-Ansicht", len(res) == 0, res)
    check("Keine JS-Fehler", not fehler_js, fehler_js[:3])
    print("== F2. InkluAgent-Kasten (Formular-Variante) ==")
    sec = pg.locator("section.inkluagent-section")
    check("Chat-Kasten vorhanden, Variante formular", sec.count() == 1 and sec.get_attribute("data-variante") == "formular", sec.get_attribute("data-variante") if sec.count() else "fehlt")
    check("Akkordeon: Knopf 'Chatbot' steht in Ueberschrift Ebene 2", pg.locator("h2#inkluagentHeading > button#inkluagentToggle").count() == 1 and pg.locator("h2#inkluagentHeading").inner_text().strip() == "Chatbot")
    check("Knopf 'Chatbot' wie bei den Alt-Texten", pg.locator("#inkluagentToggle").inner_text().strip() == "Chatbot" and pg.locator("#inkluagentToggle").get_attribute("aria-expanded") == "false")
    check("Einleitung nennt Quickinfo und Feld", "Quickinfo" in pg.locator("p.inkluagent-intro").inner_text() and "Feld 3" in pg.locator("p.inkluagent-intro").inner_text())
    pg.locator("#inkluagentToggle").click(); pg.wait_for_timeout(600)
    check("Panel offen (aria-expanded true), Eingabefeld + Senden", pg.locator("#inkluagentToggle").get_attribute("aria-expanded") == "true" and pg.locator("#inkluagentInput").count() == 1 and pg.locator("#inkluagentSendBtn").count() == 1)
    check("Platzhalter spricht von Feldern", "Feld" in (pg.locator("#inkluagentInput").get_attribute("placeholder") or ""))
    # Echter Chat-Turn ueber den Stream: Live-Zeile + Werkzeugliste unter der Antwort (28.08.2026)
    pg.fill("#inkluagentInput", "Schau bitte nach: Welche Beschriftung hat Feld 2 laut Seitentext?"); pg.keyboard.press("Enter")
    gesehen = set()
    for _ in range(60):
        pg.wait_for_timeout(500)
        st = pg.locator("#inkluagentStatus").inner_text().strip()
        if st: gesehen.add(st)
        if pg.locator(".inkluagent-message.assistant").count() >= 1 and not st: break
    check("Live-Zeile 'Ruft gerade auf' erschien", any(x.startswith("Ruft gerade auf") for x in gesehen), gesehen)
    ant = pg.locator(".inkluagent-message.assistant").last
    check("Antwort mit Werkzeugzeile 'Geprüft mit'", ant.locator(".inkluagent-message-tools").count() == 1 and "Geprüft mit" in ant.locator(".inkluagent-message-tools").inner_text(), ant.locator(".inkluagent-message-tools").inner_text() if ant.locator(".inkluagent-message-tools").count() else "fehlt")
    check("Fokus auf der Antwort", pg.evaluate("document.activeElement && document.activeElement.classList.contains('inkluagent-message')"))
    pg.reload(); pg.wait_for_timeout(3000)
    check("Werkzeugzeile auch im geladenen Verlauf", pg.locator(".inkluagent-message.assistant .inkluagent-message-tools").count() >= 1)
    pg.locator("#inkluagentToggle").click(); pg.wait_for_timeout(300)
    print("== G. Besitzer: Freigabe-Knopf ==")
    check("Knopf 'Zur Pruefung freigeben' in der Formular-Ansicht", pg.locator("#shareOpenBtn").count() == 1)
    pg.locator("#shareOpenBtn").click(); pg.wait_for_timeout(600)
    check("Einladungs-Dialog offen (modal)", pg.locator("#shareDialog").evaluate("d=>d.open") is True)
    pg.keyboard.press("Escape"); pg.wait_for_timeout(300)
    if TOKEN:
        print("== H. Gast-Ansicht ==")
        gctx = br.new_context(viewport={"width": 1280, "height": 900}, locale="de-DE"); gp = gctx.new_page()
        gfehler = []; gp.on("pageerror", lambda e: gfehler.append(str(e)))
        gp.goto(B + "/freigabe/" + TOKEN); gp.wait_for_timeout(2000)
        check("E-Mail-Gate nennt Quickinfos", "Quickinfos" in gp.locator("main").inner_text(), gp.locator("main").inner_text()[:120])
        gp.fill("#gateEmail", "gast-formular@beispiel.invalid"); gp.keyboard.press("Enter"); gp.wait_for_timeout(3000)
        check("Gast: H1 Projektname", gp.locator("h1#projectName").count() == 1)
        check("Gast: Kopfzeile nennt Felder, aber keine Stammdaten", "Felder" in gp.locator("#projectHeadInfo").inner_text() and "Stammdaten" not in gp.locator("#projectHeadInfo").inner_text(), gp.locator("#projectHeadInfo").inner_text())
        check("Gast: Knopf Pruefung abschliessen + Beenden", gp.locator("#fGuestCompleteBtn").count() == 1 and gp.locator("#guestExitBtn").count() == 1)
        check("Gast: KEIN Generieren/Export/Stammdaten/Upload/Freigeben-Knopf", gp.locator("#fGenAllBtn").count() == 0 and gp.locator("#fExportOpenBtn").count() == 0 and gp.locator("#fStammdatenBtn").count() == 0 and gp.locator("#projUpload").count() == 0 and gp.locator("#shareOpenBtn").count() == 0 and gp.locator("button[id^=feld_gen_]").count() == 0)
        check("Gast: keine Sprach-/Prompt-Auswahl", gp.locator("#altLangSelect").count() == 0 and gp.locator("#ownPromptSelect").count() == 0)
        check("Gast: KEIN Chatbot-Kasten", gp.locator("section.inkluagent-section").count() == 0)
        gp.locator("details.doc-section").first.evaluate("d=>d.open=true"); gp.locator("details.page-section").first.evaluate("d=>d.open=true"); gp.wait_for_timeout(300)
        check("Gast: keine Umbenennen/Loeschen-Knoepfe", gp.locator(".doc-actions").count() == 0)
        gcard = gp.locator("section.feld-review").first
        check("Gast: Ausschnitt-Bild ueber Freigabe-URL", "/api/freigabe/" in (gcard.locator("img.feld-ausschnitt").get_attribute("src") or ""), gcard.locator("img.feld-ausschnitt").get_attribute("src"))
        check("Gast: Urteil-Block mit Freigeben/Aenderung wuenschen", gcard.locator("button[id^=feld_btn_frei_]").count() == 1 and gcard.locator("button[id^=feld_btn_aend_]").count() == 1)
        gcard.locator("button[id^=feld_btn_frei_]").click(); gp.wait_for_timeout(1000)
        check("Gast: Freigeben -> aria-pressed true + Status Herausgeber Freigabe", gcard.locator("button[id^=feld_btn_frei_]").get_attribute("aria-pressed") == "true" and "Freigabe" in gcard.locator("[id^=feld_rev_status_]").inner_text(), gcard.locator("[id^=feld_rev_status_]").inner_text())
        check("Gast: Badge zeigt Herausgeber Freigabe", "Herausgeber Freigabe" in gcard.locator("[id^=feld_unibadge_]").inner_text(), gcard.locator("[id^=feld_unibadge_]").inner_text())
        gcard.locator("details.guest-note-edit").evaluate("d=>d.open=true"); gcard.locator("textarea[id^=feld_note_]").fill("Bitte Kontonummer statt Kundennummer."); gcard.locator("button:has-text('Anmerkung speichern')").click(); gp.wait_for_timeout(1000)
        check("Gast: Anmerkung gespeichert (Summary 'bearbeiten')", "bearbeiten" in gcard.locator("summary[id^=feld_note_summary_]").inner_text(), gcard.locator("summary[id^=feld_note_summary_]").inner_text())
        gcard.locator("textarea.quickinfo-field").fill("Vorname der Kontoinhaberin oder des Kontoinhabers"); gp.wait_for_timeout(1500)
        check("Gast: Quickinfo von Hand -> Badge 'vom Gast bearbeitet'", "vom Gast bearbeitet" in gcard.locator("[id^=feld_status_]").inner_text(), gcard.locator("[id^=feld_status_]").inner_text())
        gp.locator("#fGuestCompleteBtn").click(); gp.wait_for_timeout(600)
        check("Gast: Abschluss-Dialog offen", gp.locator("#fGuestCompleteDialog").evaluate("d=>d.open") is True)
        gp.fill("#fGuestCompleteMsg", "Klicktest: Pruefung durch."); gp.locator("#fGuestCompleteSend").click(); gp.wait_for_timeout(3000)
        check("Gast: Dankeseite mit Rueckweg", gp.locator("#guestThanksHeading").count() == 1 and gp.locator("button:has-text('Zurück zum Projekt')").count() == 1)
        gp.locator("button:has-text('Zurück zum Projekt')").click(); gp.wait_for_timeout(2500)
        check("Gast: Rueckweg fuehrt ins Projekt", gp.locator("h1#projectName").count() == 1)
        gp.add_script_tag(url=AXE); gp.wait_for_timeout(500)
        gp.locator("details.doc-section").first.evaluate("d=>d.open=true"); gp.locator("details.page-section").first.evaluate("d=>d.open=true")
        gres = gp.evaluate("axe.run(document, {runOnly:{type:'tag', values:['wcag2a','wcag2aa','wcag21a','wcag21aa']}}).then(r=>r.violations.map(v=>v.id+': '+v.nodes.length+' '+v.nodes.slice(0,2).map(n=>n.target.join(' ')).join(' | ')))")
        check("Gast: axe 0 Verstoesse", len(gres) == 0, gres)
        check("Gast: keine JS-Fehler", not gfehler, gfehler[:3])
        gp.screenshot(path=os.path.join(SHOTS, "f_gast.png"), full_page=False)
        print("== I. Besitzer sieht das Urteil ==")
        pg.reload(); pg.wait_for_timeout(3000)
        pg.locator("details.doc-section").first.evaluate("d=>d.open=true"); pg.locator("details.page-section").first.evaluate("d=>d.open=true"); pg.wait_for_timeout(300)
        ocard = pg.locator("section.feld-review").first
        check("Besitzer: Badge 'Herausgeber Freigabe — mit Anmerkung'", "Herausgeber Freigabe" in ocard.locator("[id^=feld_unibadge_]").inner_text() and "mit Anmerkung" in ocard.locator("[id^=feld_unibadge_]").inner_text(), ocard.locator("[id^=feld_unibadge_]").inner_text())
        ka = ocard.locator("details.kundenanmerkung")
        if ka.count(): ka.first.evaluate("d=>d.open=true"); pg.wait_for_timeout(200)
        check("Besitzer: Anmerkung des Gastes als Klappe", ka.count() == 1 and "Kontonummer" in ka.first.inner_text(), ka.first.inner_text() if ka.count() else "keine Klappe")
        check("Besitzer: keine Urteil-Knoepfe", ocard.locator("button[id^=feld_btn_frei_]").count() == 0)
    br.close()
print(f"\nErgebnis: {ok} OK, {fehler} FEHLER")
sys.exit(1 if fehler else 0)
